/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "node_modules/react-daisyui/dist/**/*.js",
    "node_modules/daisyui/dist/**/*.js",
  ],
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      'light',
      { 
        myluxuryrosegoldblush: {
          "primary": "#B76E79",
          "primary-content": "#ffffff",
          "secondary": "#F5E7E7",
          "secondary-content": "#B76E79",
          "accent": "#A55858",
          "accent-content": "#ffffff",
          "neutral": "#FAF0F0",
          "neutral-content": "#222222",
          "base-100": "#ffffff",
          "base-200": "#F8EFEF",
          "base-300": "#F5E7E7",
          "base-content": "#222222",
          "info": "#E9967A",
          "success": "#8FBC8F",
          "warning": "#F4D03F",
          "error": "#E57373",
          "--gold": "#B76E79",
          "--cool-gray": "#F5E7E7",
          "--royal-blue": "#A55858",
          "--soft-white": "#FAF0F0",
          "--pure-white": "#ffffff",
          "--primary-soft": "rgba(183, 110, 121, 0.1)",
          "--secondary-soft": "rgba(245, 231, 231, 0.1)",
          "--accent-soft": "rgba(165, 88, 88, 0.1)",
          "--base-neutral": "#F8EFEF",
        },
      },
      {
        myluxuryfitness: {
          "primary": "#c99a3f",
          "primary-content": "#ffffff",
          "secondary": "#ececec",
          "secondary-content": "#222222",
          "accent": "#0056b3",
          "accent-content": "#ffffff",
          "neutral": "#f8f8f8",
          "neutral-content": "#222222",
          "base-100": "#ffffff",
          "base-200": "#f2f2f2",
          "base-300": "#e6e6e6",
          "base-content": "#222222",

          "info": "#2094f3",
          "success": "#009485",
          "warning": "#ff9900",
          "error": "#ff5724",

          "--gold": "#c99a3f",
          "--cool-gray": "#ececec",
          "--royal-blue": "#0056b3",
          "--soft-white": "#f8f8f8",
          "--pure-white": "#ffffff",

          "--primary-soft": "rgba(201, 154, 63, 0.1)",
          "--secondary-soft": "rgba(236, 236, 236, 0.1)",
          "--accent-soft": "rgba(0, 86, 179, 0.1)",
          "--base-neutral": "#f2f2f2",
        },
      },
      {
        myluxuryred: {
          "primary": "#B22222",
          "primary-content": "#ffffff",
          "secondary": "#F5E0DC",
          "secondary-content": "#660000",
          "accent": "#7D1313",
          "accent-content": "#ffffff",
          "neutral": "#FAF3F3",
          "neutral-content": "#222222",
          "base-100": "#ffffff",
          "base-200": "#f8eaea",
          "base-300": "#f0dcdc",
          "base-content": "#222222",

          "info": "#db4c40",
          "success": "#00a86b",
          "warning": "#ffb703",
          "error": "#d90429",

          "--gold": "#8B0000",
          "--cool-gray": "#F5E0DC",
          "--royal-blue": "#9D1313",
          "--soft-white": "#FAF3F3",
          "--pure-white": "#ffffff",

          "--primary-soft": "rgba(178, 34, 34, 0.1)",
          "--secondary-soft": "rgba(245, 224, 220, 0.1)",
          "--accent-soft": "rgba(125, 19, 19, 0.1)",
          "--base-neutral": "#F8EAEA",
        },
      },
      {
        myluxurygreen: {
          "primary": "#2E8B57",
          "primary-content": "#ffffff",
          "secondary": "#D4EED1",
          "secondary-content": "#1E5631",
          "accent": "#1E5631",
          "accent-content": "#ffffff",
          "neutral": "#EFFAF3",
          "neutral-content": "#222222",
          "base-100": "#ffffff",
          "base-200": "#E5F5E8",
          "base-300": "#D4EED1",
          "base-content": "#222222",

          "info": "#4caf50",
          "success": "#00a86b",
          "warning": "#fbc02d",
          "error": "#d32f2f",

          "--gold": "#2E8B57",
          "--cool-gray": "#D4EED1",
          "--royal-blue": "#1E5631",
          "--soft-white": "#EFFAF3",
          "--pure-white": "#ffffff",

          "--primary-soft": "rgba(46, 139, 87, 0.1)",
          "--secondary-soft": "rgba(212, 238, 209, 0.1)",
          "--accent-soft": "rgba(30, 86, 49, 0.1)",
          "--base-neutral": "#E5F5E8",
        },
      },
      {
        myluxurypurple: {
          "primary": "#6A0DAD",
          "primary-content": "#ffffff",
          "secondary": "#E8D5F5",
          "secondary-content": "#4B0082",
          "accent": "#4B0082",
          "accent-content": "#ffffff",
          "neutral": "#F7F0FA",
          "neutral-content": "#222222",
          "base-100": "#ffffff",
          "base-200": "#F0E6F7",
          "base-300": "#E8D5F5",
          "base-content": "#222222",

          "info": "#957dad",
          "success": "#7b68ee",
          "warning": "#ffb74d",
          "error": "#e91e63",

          "--gold": "#6A0DAD",
          "--cool-gray": "#E8D5F5",
          "--royal-blue": "#4B0082",
          "--soft-white": "#F7F0FA",
          "--pure-white": "#ffffff",

          "--primary-soft": "rgba(106, 13, 173, 0.1)",
          "--secondary-soft": "rgba(232, 213, 245, 0.1)",
          "--accent-soft": "rgba(75, 0, 130, 0.1)",
          "--base-neutral": "#F0E6F7",
        },
      },
      {
        myluxuryblue: {
          "primary": "#1E3A8A",
          "primary-content": "#ffffff",
          "secondary": "#CBD5E1",
          "secondary-content": "#0F172A",
          "accent": "#0F172A",
          "accent-content": "#ffffff",
          "neutral": "#E0F2FE",
          "neutral-content": "#222222",
          "base-100": "#ffffff",
          "base-200": "#D7E7F9",
          "base-300": "#CBD5E1",
          "base-content": "#222222",

          "info": "#42a5f5",
          "success": "#4caf50",
          "warning": "#ffa726",
          "error": "#d32f2f",

          "--gold": "#1E3A8A",
          "--cool-gray": "#CBD5E1",
          "--royal-blue": "#0F172A",
          "--soft-white": "#E0F2FE",
          "--pure-white": "#ffffff",

          "--primary-soft": "rgba(30, 58, 138, 0.1)",
          "--secondary-soft": "rgba(203, 213, 225, 0.1)",
          "--accent-soft": "rgba(15, 23, 42, 0.1)",
          "--base-neutral": "#D7E7F9",
        },
      },
    ],
  },
  theme: {
    extend: {
      colors: {
        "gold": "var(--gold)",
        "cool-gray": "var(--cool-gray)",
        "royal-blue": "var(--royal-blue)",
        "soft-white": "var(--soft-white)",
        "pure-white": "var(--pure-white)",

        "primary-soft": "var(--primary-soft)",
        "secondary-soft": "var(--secondary-soft)",
        "accent-soft": "var(--accent-soft)",
        "base-neutral": "var(--base-neutral)",
      },
    },
  },
};
