/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "node_modules/react-daisyui/dist/**/*.js",
    "node_modules/daisyui/dist/**/*.js",
  ],
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      { 
        myluxurysapphire: {
          "primary": "#1E3A8A",
          "primary-content": "#ffffff",
          "secondary": "#CBD5E1",
          "secondary-content": "#0F172A",
          "accent": "#0F172A",
          "accent-content": "#ffffff",
          "neutral": "#E0F2FE",
          "neutral-content": "#222222",
          "base-100": "#ffffff",
          "base-200": "#D7E7F9",
          "base-300": "#CBD5E1",
          "base-content": "#222222",
          "info": "#42a5f5",
          "success": "#4caf50",
          "warning": "#ffa726",
          "error": "#d32f2f",
          "--gold": "#1E3A8A",
          "--cool-gray": "#CBD5E1",
          "--royal-blue": "#0F172A",
          "--soft-white": "#E0F2FE",
          "--pure-white": "#ffffff",
          "--primary-soft": "rgba(30, 58, 138, 0.1)",
          "--secondary-soft": "rgba(203, 213, 225, 0.1)",
          "--accent-soft": "rgba(15, 23, 42, 0.1)",
          "--base-neutral": "#D7E7F9",
        },
        myluxuryruby: {
          "primary": "#B22222",
          "primary-content": "#ffffff",
          "secondary": "#F5E0DC",
          "secondary-content": "#660000",
          "accent": "#7D1313",
          "accent-content": "#ffffff",
          "neutral": "#FAF3F3",
          "neutral-content": "#222222",
          "base-100": "#ffffff",
          "base-200": "#f8eaea",
          "base-300": "#f0dcdc",
          "base-content": "#222222",
          "info": "#db4c40",
          "success": "#00a86b",
          "warning": "#ffb703",
          "error": "#d90429",
          "--gold": "#8B0000",
          "--cool-gray": "#F5E0DC",
          "--royal-blue": "#9D1313",
          "--soft-white": "#FAF3F3",
          "--pure-white": "#ffffff",
          "--primary-soft": "rgba(178, 34, 34, 0.1)",
          "--secondary-soft": "rgba(245, 224, 220, 0.1)",
          "--accent-soft": "rgba(125, 19, 19, 0.1)",
          "--base-neutral": "#F8EAEA",
        },
        myluxuryonyx: {
          "primary": "#353839",
          "primary-content": "#ffffff",
          "secondary": "#C4C9CC",
          "secondary-content": "#1D2025",
          "accent": "#1D2025",
          "accent-content": "#ffffff",
          "neutral": "#D8E1E6",
          "neutral-content": "#222222",
          "base-100": "#ffffff",
          "base-200": "#E6E8EC",
          "base-300": "#C4C9CC",
          "base-content": "#222222",
          "info": "#6C757D",
          "success": "#28A745",
          "warning": "#FFC107",
          "error": "#DC3545",
          "--gold": "#353839",
          "--cool-gray": "#C4C9CC",
          "--royal-blue": "#1D2025",
          "--soft-white": "#D8E1E6",
          "--pure-white": "#ffffff",
          "--primary-soft": "rgba(53, 56, 57, 0.1)",
          "--secondary-soft": "rgba(196, 201, 204, 0.1)",
          "--accent-soft": "rgba(29, 32, 37, 0.1)",
          "--base-neutral": "#E6E8EC",
        },
        myluxurydiamond: {
          "primary": "#1E3A8A",  
          "primary-content": "#ffffff", 
          "secondary": "#D8D8D8", 
          "secondary-content": "#212121", 
          "accent": "#FFC107",
          "accent-content": "#212121",
          "neutral": "#F1F1F1",
          "neutral-content": "#212121",
          "base-100": "#ffffff",
          "base-200": "#F3F3F3",
          "base-300": "#D8D8D8",
          "base-content": "#212121",
          "info": "#4F83CC",
          "success": "#66BB6A",
          "warning": "#FFB74D",
          "error": "#EF5350",
          "--gold": "#1E3A8A",
          "--cool-gray": "#D8D8D8",
          "--royal-blue": "#1D1D1B",
          "--soft-white": "#F1F1F1",
          "--pure-white": "#ffffff",
          "--primary-soft": "rgba(30, 58, 138, 0.1)",
          "--secondary-soft": "rgba(216, 216, 216, 0.1)",  
          "--accent-soft": "rgba(255, 193, 7, 0.1)", 
          "--base-neutral": "#F3F3F3",
        },
        myluxurylavender: {
          "primary": "#9B4D96",
          "primary-content": "#ffffff",
          "secondary": "#D3AED8",
          "secondary-content": "#3E1F47",
          "accent": "#7A5C9D",
          "accent-content": "#ffffff",
          "neutral": "#E8E0F1",
          "neutral-content": "#1C0F26",
          "base-100": "#ffffff",
          "base-200": "#F2E6F7",
          "base-300": "#D3AED8",
          "base-content": "#1C0F26",
          "info": "#AB8B9F",
          "success": "#81C784",
          "warning": "#FFEB3B",
          "error": "#E57373",
          "--gold": "#9B4D96",
          "--cool-gray": "#D3AED8",
          "--royal-blue": "#3E1F47",
          "--soft-white": "#E8E0F1",
          "--pure-white": "#ffffff",
          "--primary-soft": "rgba(155, 77, 150, 0.1)",
          "--secondary-soft": "rgba(211, 174, 216, 0.1)",
          "--accent-soft": "rgba(122, 92, 157, 0.1)",
          "--base-neutral": "#F2E6F7",
        },
        myluxuryopal: {
          "primary": "#A8D8D8",
          "primary-content": "#1A1A1A",
          "secondary": "#E0F7F7",
          "secondary-content": "#00695C",
          "accent": "#00796B",
          "accent-content": "#ffffff",
          "neutral": "#B2DFDB",
          "neutral-content": "#1A1A1A",
          "base-100": "#ffffff",
          "base-200": "#E0F7F7",
          "base-300": "#A8D8D8",
          "base-content": "#1A1A1A",
          "info": "#42a5f5",
          "success": "#66BB6A",
          "warning": "#FFEB3B",
          "error": "#EF5350",
          "--gold": "#A8D8D8",
          "--cool-gray": "#E0F7F7",
          "--royal-blue": "#1A1A1A",
          "--soft-white": "#B2DFDB",
          "--pure-white": "#ffffff",
          "--primary-soft": "rgba(168, 216, 216, 0.1)",
          "--secondary-soft": "rgba(224, 247, 247, 0.1)",
          "--accent-soft": "rgba(0, 121, 107, 0.1)",
          "--base-neutral": "#E0F7F7",
        },
    },
    ],
  },
};
